### ISSUE TITLE
More deps are needed for real world app

### ISSUE THREAD

**Issue by octavz** [kitlangton/zio-magic#4]
Hi,

On the main app layer i have more than deps. So I think it needs more, or just let me provide a list or something.

**Comment by kitlangton** [comment]
Whoops. Didn’t mean to close!
Cool ;) Thanks for the real world feedback. The only limit to adding more overloads is that IntelliJ can get overwhelmed. 

Unfortunately, a list will not work because I need access to the types, at least, I believe it won’t—I’ll do some more explorations, as it would be nicer to both implement and use if I could accept variadic arguments.

In case that is not possible, how many layers do you currently need? I originally had 22, but it got a little slow w/ IDEA. 

For now though, I also made a version `ZLayer[Your with Layer].fromMagic(...)` which performs the same way. This will let you break out large sub graphs and overcome the limit for now.

**Comment by kitlangton** [comment]
OH! IT IS POSSIBLE! Bless you @octavz! You just helped me delete 90% of the code in this thing _and_ simplified the call-site.

**Comment by kitlangton** [comment]
` 14 files changed, 98 insertions(+), 2831 deletions(-) ` _and_ it works better <3

**Comment by octavz** [comment]
22 is prett yrandom, we have small modules and i easily gathered around 25, given the fact that every zio lib will also provide functionality as a layer is easy to pile up. Ofc we used ++ but I'd prefer to not use that at all unless tgey are top level.

**Comment by octavz** [comment]
Also i couldn't figure out how to use provideSome with a lot of layers.  Having  provideSomeMagic in between could help with the layers pile, but it doesn't work with a lot of layers.

Other than that we already committed code in repos with zio-magic. :)  Great work. Thanks!

**Comment by kitlangton** [comment]
Oh! Now it should work w/ varargs actually. So no limits! @octavz

**Comment by kitlangton** [comment]
Try using the non-snapshot: `"io.github.kitlangton" %% "zio-magic" % "0.1.3"
